config/routes.rb
Store::Application.routes.draw do

  get "activities/index"
	get 'tours/search'
  post '/profiles/editr/:id', to: 'profiles#editr', as: 'editr'

  resources :friendships

  resources :ratings, only: :update

  resources :bookings

  resources :purchases

  resources :pictures

  resources :profiles

  resources :locations do
    resources :comments
    resources :reviews
  end

  resources :tours do
	  resources :comments
    resources :reviews
  end

  resources :activities

  get "home/index"
  get "home/about"
  get "home/contact"

  resources :products

  root 'home#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
		@tour = Tour.find params[:tour_id]
    @purchase = @tour.purchases.new(purchase_params)
		@purchase.profile_id = Profile.find_by_user_id current_user.id

    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase }
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params.require(:purchase).permit(:number_of_reservations, :price)
    end
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_of_reservations %><br>
    <%= f.number_field :number_of_reservations %>
  </div>

  <div class="actions">
    <%= hidden_field_tag :tour_id, params[:tour_id]%>
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<table>
  <thead>
    <tr>
      <th>Number of reservations</th>

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.number_of_reservations %></td>

        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p>
  <strong>Number of reservations:</strong>
  <%= @purchase.number_of_reservations %>
</p>

<p>
  <strong>tour id</strong>
  <%= @purchase.tour_id %>
</p>

<p>
  <strong>username</strong>
  <%= @purchase.profile_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @purchase.tour.price *  @purchase.number_of_reservations %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>