config/routes.rb
Store::Application.routes.draw do

  get "activities/index"
	get 'tours/search'
  post '/profiles/editr/:id', to: 'profiles#editr', as: 'editr'

  resources :friendships

  resources :ratings, only: :update

  resources :bookings

  resources :purchases

  resources :pictures

  resources :profiles

  resources :locations do
    resources :comments
    resources :reviews
  end

  resources :tours do
	  resources :comments
    resources :reviews
  end

  resources :activities

  get "home/index"
  get "home/about"
  get "home/contact"

  resources :products

  root 'home#index'

  devise_for :users, :controllers => { :registrations => "registrations" }

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
	  user ||= User.new # guest user (not logged in)
	  if user.role == "admin"
		  can :manage, :all
		  can :update, :all
	  else
		  can :read, :all
	  end

	  can :manage, :all if user.role == "admin"
	  can :update, :all if user.role == "admin"
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :user
	belongs_to :tour

  # validates :user_id, :uniqueness => { :scope => :tour_id,
  #                                      :message => "Users may only book once." }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include  PublicActivity::Common
 # tracked except: :update, owner: ->(controller, model) { controller && controller.current_user }



  has_ancestry
	belongs_to :commentable, polymorphic: true
	belongs_to :tour, :class_name => 'Tour', :foreign_key => 'commentable_id'
  belongs_to :location, :class_name => 'Location', :foreign_key => 'commentable_id'
  belongs_to :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/location.rb
class Location < ActiveRecord::Base
	
	has_attached_file :avatar, :styles => {:medium => "300x300#", :thumb => "100x100#"}, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	has_many :tours, dependent: :destroy
	has_many :reviews, as: :reviewable
	has_many :comments, as: :commentable
  has_many :pictures
	has_many :ratings, as: :ratable
	

	validates :name, presence: true
	validates :province, presence: true
	validates :description, presence: true
	
	def average_rating
			ratings.sum(:score) / ratings.size
	end
	
	def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
	end
	
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  belongs_to :location
  belongs_to :tour
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	has_attached_file :avatar, :styles => {:medium => "300x300#", :thumb => "100x100#"}, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	
	belongs_to :user
	has_many :purchases


  GENDER = %w{ m f }

  GENDER.each_with_index do |meth, index|
    define_method("#{meth}?") { type == index }
  end
	
	def self.search(search)
    if search
      where('first_name LIKE ?', "%#{search}%")
    else
      scoped
    end
	end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	belongs_to :profile
	belongs_to :tour
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :ratable, polymorphic: true
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  include  PublicActivity::Common
	belongs_to :reviewable, polymorphic: true
  belongs_to :tour, :class_name => 'Tour', :foreign_key => 'commentable_id'
  belongs_to :user

  scope :review_type, -> (review_type) { where review_type: review_type }

  RTYPE = %w{ couple friends family_with_young_children family solo }

  RTYPE.each_with_index do |meth, index|
    define_method("#{meth}?") { type == index }
  end

  validates :content, presence: true
  # validates :user_id, :uniqueness => { :scope => :product_id,
#                                       :message => "Users may only write one review per product." }

end

app/models/tour.rb
class Tour < ActiveRecord::Base


  include PublicActivity::Common


  belongs_to :location
	has_and_belongs_to_many :users
	has_many :reviews, as: :reviewable
	has_many :bookings
	has_many :users, :through => :bookings
	has_many :comments, :as => :commentable, :dependent => :destroy
  has_many :pictures
	has_many :ratings, as: :ratable




	validates :departure_location, presence: true
	validates :quorum, presence: true,
	          :numericality => {greater_than_or_equal_to: 0, only_integer: true}
	validates :price, presence: true,
	          :numericality => {greater_than_or_equal_to: 0, only_integer: true}

	def self.search(search)
    if search
      where('quorum LIKE ?', "%#{search}%")
    else
      scoped
    end
	end
	
	def average_rating
			if ratings.size==0
			ratings.sum(:score)
			else
			ratings.sum(:score) / ratings.size
		end	
	end

	def bookings_total
		self.users.count
	end
	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ROLES = %w[admin leader tourist]

  has_many :ratings

  has_one :profile
  has_many :reviews
  has_many :comments
  has_many :bookings
  has_many :tours, through: :bookings
  has_many :comments
  has_many :reviews
  has_many :pictures

  has_many :friendships
  has_many :friends, through: :friendships

  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end

end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
      helper_method :sort_column, :sort_direction    
      def sort_column  
      Tour.column_names.include?(params[:sort]) ? params[:sort] : "quorum"  
    end   
    
	def sort_direction  
		%w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"  
	end
  def index
  end

  def about
  end
  
  def search
   @tours = Tour.search(params[:search])#.order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
	@locations = Location.search(params[:search])
	@profiles = Profile.search(params[:search])
  end

  def contact
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|

			content_tag(:div, render(comment))
		end.join.html_safe
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def reviews(reviews)
    reviews.map do |review|
      content_tag(:div, render(review))
    end.join.html_safe
  end
end

app/helpers/tours_helper.rb
module ToursHelper
    def index  
      @tours = Tour.order(params[:sort] + ' ' + params[:direction])  
    end  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/home/_locations_searched_from_home.html.erb
<table>
  <thead>
    <tr>
      <th><%= t("name") %></th>
      <th><%=  t("province") %></th>
      <th><%=  t("avrage rating") %></th>
	  <th></th>	
    </tr>
  </thead>

  <tbody>
  <% for location in @locations %>
      <tr>
        <td><%= location.name %></td>
        <td><%= location.province %></td>
        <td><div id="star-<%= location.id%>"></div></td> 
        <td>
                 <ul class="button-group">
            <li><%= link_to 'Show',location, class: 'button secondary tiny' %></li>
          </ul> 
        </td>       
      </tr>
      	  <script>
	  $('#star-<%= location.id%>').raty({
		readOnly: true,
		score: <%= location.average_rating %>,
		path: '/assets'
	  });
	</script>         

    <% end %>
  </tbody>
</table>

<br>

app/views/home/_profiles_searched_from_home.html.erb
<table class="profiels" >
  <thead>
    <tr>
      <th><%= t('First name') %></th>
      <th><%= t('Last name') %></th>
      <th><%= t('City') %></th>
      <th><%= t('Province') %></th>
      <th><%= t('Date of birth') %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% for profile in @profiles %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= profile.city %></td>
        <td><%= profile.province %></td>
        <td><%= profile.date_of_birth %></td>
        <td><%= link_to 'Show', profile %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/home/_tours_searched_from_home.html.erb
<table class="pretty">
  <tr>
    <th><%= 'تاریخ رفت' %></th>
    <th><%=  'زمان رفت' %></th>
    <th>مقصد</th>
    <th><%= 'ظرفیت' %></th>
    <th>افراد ثبت نام کرده'</th>
    <th><%=  'قیمت' %></th>
    <th><%=  t('avrage rating') %></th>
    <th></th>
  </tr>
  <% for tour in @tours %>
       <tr>
        <td><%= JalaliDate.to_jalali(tour.departure_date).strftime("%d/%m/%Y") %></td>
        <td><%= tour.departure_time %></td>
        <td><%= link_to tour.location.name, tour.location %></td>
        <td><%= tour.quorum %></td>
        <td><%= tour.users.count %></td>
        <td><%= tour.price %></td>
        <td><div id="star-<%= tour.id%>"></div></td>
        <td>
          <ul class="button-group">
            <li><%= link_to 'Show', tour, class: 'button secondary tiny' %></li>
          </ul>
        </td>
      </tr>
  <script>
  $('#star-<%= tour.id%>').raty({
    readOnly: true,
    score: <%= tour.average_rating %>,
    path: '/assets'
  });
</script>         
  <% end %>
</table>

app/views/home/about.html.erb
<div class="row">

  <div class="large-6 columns" id="writers">

    <dl class="tabs" data-tab>
      <dd class="active"><a href="#panel2-1">امیر وکیلی تهامی</a></dd>
      <dd><a href="#panel2-2">مهرداد فرخی</a></dd>
    </dl>
    <div class="tabs-content" >
      <div class="content active" id="panel2-1">
        <div class="small-6 columns"><p>


          </p></div>
        <div class="small-6 columns">
          <%= image_tag "amir-photo.jpg" %></div>
      </div>
      <div class="content" id="panel2-2">
        <div class="small-6 columns"><%= image_tag "f1.jpg" %></div>
        <div class="small-6 columns"><p>
  
          </p></div>
      </div>
    </div>


  </div>

  <div class="large-6 columns">
    <h1>درباره ی ما</h1>

    <p>
ابن وب سایت به اعضای خود امکان شرکت در انواع تورها به مکانهای دیدنی سراسر ایران را می دهد. این وب سایت پاسخی است برای افرادی که به شرکت در مسافرت علاقه مند هستند ولی زمان کافی برای برنامه ریزی آن یا گشتن دنبال تور مناسب خود را ندارند. مقصد خود را از میان مکان های انتخاب شده توسط تور لیدر های ما انتخاب کنید و توری ه مناسب خود شما است انتخاب کنید. اگر ایده ی جدیدی برای تور دارید، پیشنهاد بدهید و از دوستان خود بخواهید از آ طرفداری کنند. با افراد همسلیقه ی ود آشنا شوید و با آنها به جاذبه های موردعلاقه ی خود بروید. تنها کاری که شما لازم است انجام دهید، بستن کوله پشتی خود است!
       </p>

    <p>

      </p>
  </div>
</div>

app/views/home/contact.html.erb
<div class="row">
  <div class="large-4 columns large-push-8">
    <p>
      شما می توانید از طریق فرم مقابل با ما تماس بگیرید یا هم با استفاده از یکی از لینک های زیر:<br/>
    </p>
    <ul>

      <li><a href="mailto:#">amirvt92@yahoo.com</a></li>
      <li><a href="mailto:#">mfthepop@yahoo.com</a></li>
      
    </ul>
  </div>


  <div class="large-8 columns large-pull-4">
    <fieldset>
      <legend>
        Contact Us:
      </legend>
      <div class="row collapse">
        <div class="small-9  columns">
          <input placeholder="نام" type="text" name="name" maxlength="100">
        </div>
        <div class="small-3  columns">
          <span class="postfix">?</span>
        </div>
      </div>
      <div class="row collapse">
        <div class="small-9  columns">
          <input placeholder="email" type="email" name="email" maxlength="100" required="required">
        </div>
        <div class=" small-3 columns">
          <span class="postfix">@</span>
        </div>
      </div>

      <div class="row collapse">
        <div class="small-12  columns">
          <textarea name="content" cols="20" rows="4" placeholder="enter yout comments..."></textarea>
        </div>
      </div>

      <ul class="button-group right">
        <li><a href="#" class="button success">ارسال</a></li>
      </ul>
    </fieldset>
  </div>



</div>

app/views/home/index.html.erb
<!--content-->
<!-- First Band (Slider) -->

<!--Orbit-->

<div class="row">
  <div class="large-12 large-centered columns">
    <div class="orbit-container">
      <ul data-orbit data-options="timer_speed:2500">
        <li><%= image_tag "banners/1.jpg" %>

          <div class="orbit-caption">به لیدر های مان تور به مکان های جدید پیشنهاد دهید</div>
        </li>
        <li><%= image_tag "banners/2.jpg" %>

          <div class="orbit-caption">با معرفی دوستان خود به سایت ما، از تخفیف های ویژه برخوردار شوید</div>
        </li>
        <li><%= image_tag "banners/3.jpg" %>

          <div class="orbit-caption">به لیدر های مان تور به مکان های جدید پیشنهاد دهید</div>
        </li>
        <li><%= image_tag "banners/4.jpg" %>

          <div class="orbit-caption">به لیدر های مان تور به مکان های جدید پیشنهاد دهید</div>
        </li>
        <li><%= image_tag "banners/5.jpg" %>

          <div class="orbit-caption">به لیدر های مان تور به مکان های جدید پیشنهاد دهید</div>
        </li>
      </ul>
    </div>
  </div>
</div>

<hr>

<!-- Call to Action Panel -->
<div class="row">
  <div class="large-12 columns">

    <div class="panel">
      <h1>سفرک!</h1>

      <div class="row">


        <div class="large-9 large-push-3  columns">
          <p> خسته وکوفته اید؟<br/>
            احتیاج به تنوع دارید؟<br/>
            می خواهید مشافرت برید اما حال و حو
            صله تنظیم آن یا وقت کافی برای رفتن را ندارید؟<br/>
            توریستینگ راه حل شماست!<br/>
            با پیوستن به مجموعه ی ما شما می توانید با کمترین هزینه و درد سر تور یک روزه مناسب خود را انتخاب
            کنید و همراه دوستان جدید یا قدیمی به مکان های تاریخی تفریحی که همیشه دوست داشتید بریدسفر
            کنیدد.<br/>


          </p>
        </div>

        <div class="large-3  columns large-pull-9">
          <ul class="my-vertical-button-bar">
            <!--<li><a href="/" class="radius button success">عضویت</a></li>-->
            <li><%= link_to "عضویت", new_user_registration_path, :class => "button radius success" %></li>
            <li><%= link_to "بازدید تورها", tours_path, :class => "button radius success" %></li>
            <!--<li><%= link_to 'dssdsdsd', controller: 'tours' %></li>-->
          </ul>

        </div>

      </div>
    </div>

  </div>
</div>


<!-- Three-up Content Blocks -->

<div class="row three-columns" data-equalizer>
  <div class="large-4 columns " >
    <div class="panel" data-equalizer-watch>
      <%= image_tag "misc/1.jpg" %>
      <h4>آبشار یخی</h4>

      <p> 
      آبشار یخی آبشاری است در ارتفاع ۵۱۰۰ متری از جبههٔ جنوبی کوه دماوند.

ارتفاع این آبشار بین ۷[۱] تا ۱۲ متر گفته شده و به جز در زمان‌های کوتاهی از تابستان که برای مدت کوتاهی باریکهٔ آبی از کنار آن جاری می‌شود، در سایر زمان‌ها یخ‌زده است. دسترسی به این آبشار، نیازمند منحرف‌شدن از مسیر اصلی جبههٔ جنوبی است.

این آبشار با قرار داشتن در ارتفاع ۵۱۰۰ متری، از نظر ارتفاع از سطح دریا مرتفع‌ترین آبشار خاورمیانه است

        </p>
    </div>
  </div>

  <div class="large-4 columns " >
    <div class="panel" data-equalizer-watch>
      <%= image_tag "misc/2.jpg" %>
      <h4>کویر شهداد</h4>

      <p>
شهداد با نام تاریخی خبیص و جمعیت ۱۵۰۰۰ نفری، در ۷۰ کیلومتری شمال شرق کرمان، در حاشیه باختری لوت مرکزی قرار گرفته‌است و کویری‌ترین بخش استان کرمان به شمار می‌رود. این ناحیه از کرمان، هیچگاه مورد توجه باستان شناسان نبود، زیرا تصور وجود تمدن باستانی در صحرای خشک لوت غیر ممکن بود. اولین هئیت کاوش در سالهای ۱۳۴۶ به سرپرستی دکتر احمد مستوفی- از موسسه جغرافیایی دانشگاه تهران – برای بررسی موقعیت جغرافیایی دشت لوت و اطراف آن وارد آنجا شدند و در حین اکتشافات خود « چاله تکاب » به تعدادی سفال برخورد کردند که قسمتی از آنها از زمین بیرون و این آثار نشان از وجود تمدنی پیشرفته در این ناحیه بود. درفش شهداد کهن‌ترین درفش یافت شده در ایران است که اکنون در موزه ملی نگه داری می‌شود 
        </p>
    </div>
  </div>

  <div class="large-4 columns " >
    <div class="panel" data-equalizer-watch>
      <%= image_tag "misc/3.jpg" %>
      <h4>قله توچال</h4>

      <p> 
توچال قلّه‌ای در شمال تهران و به ارتفاع ۳۹۶۲ متر می‌باشد که بخشی از دامنه رشته‌کوه‌های البرز است. دامنهٔ جنوبی توچال مجاور با شهر تهران و قلهٔ آن مشرف به این شهر است.

مشهورترین و پر رفت و آمدترین پناهگاه‌ها و جان‌پناه‌های توچال به ترتیب از شرق به غرب دارآباد، کلک‌چال، شروین، شیرپلا، جان پناه قله توچال، امیری، هتل اوسون، ایستگاه پنجم تله کابین، اسپیدکمر و پلنگ‌چال هستند که همگی آن‌ها مشرف به تهران هستند. 
        </p>
    </div>
  </div>

</div>


<!--calender & newsletter-->
<div class="row" data-equalizer>
  <div class="large-6 columns">
    <div class="panel callout" data-equalizer-watch>
      <h3>فروردین</h3>
      <table id="calender">
        <tr>
          <th>شنبه</th>
          <th>یک شنبه</th>
          <th>دو شنبه</th>
          <th>سه شنبه</th>
          <th>چهار شنبه</th>
          <th>پنج شنبه</th>
          <th>جمعه</th>
        </tr>
        <tr>
          <td>1</td>
          <td>2</td>
          <td>3</td>
          <td>4</td>
          <td>5</td>
          <td>6</td>
          <td>7</td>
        </tr>
        <tr>
          <td>8</td>
          <td>9</td>
          <td>10</td>
          <td class="date-canceled">11</td>
          <td>12</td>
          <td>13</td>
          <td>14</td>
        </tr>
        <tr>
          <td class="date-signed-up">15</td>
          <td>16</td>
          <td>17</td>
          <td>18</td>
          <td>19</td>
          <td>20</td>
          <td>21
        </tr>
        </tr>
        <tr>
          <td>22</td>
          <td class="date-upcoming">23</td>
          <td>24</td>
          <td>25</td>
          <td>26</td>
          <td>27</td>
          <td>28</td>
        </tr>
        <tr>
          <td>29</td>
          <td>30</td>
          <td>31</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="large-6 columns ">
    <div class="panel callout"><h3>خبرنامه</h3>

      <div id="news">

      </div>
    </div>
  </div>

</div>

<!-- Call to Action Panel -->
<div class="row">
  <div class="large-12 columns">

    <div class="panel">
      <h4> با ما تماس بگیریید!</h4>

      <div class="row">
        <div class="large-9 columns large-push-3">
          <p>منتظر نظرات، .یشنهادات و انتقادهای شما هستیم</p>
        </div>
        <div class="large-3 columns large-pull-9">
          <a href="/home/contact" class="radius button right">تماس با ما</a>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/home/search.html.erb
<dl class="tabs right" data-tab>
  <dd class="active"><a href="#panel2-4"><%= t("tours") %></a></dd>
  <dd><a href="#panel2-3"><%= t("locations")%></a></dd>
  <dd><a href="#panel2-2"><%= t("profiles")%></a></dd>

</dl>
<div class="tabs-content">
  <div  class="content active" id="panel2-4">
    <p><div id="tours" ><%= render :partial => "home/tours_searched_from_home" %></div></p>
  </div> 
  
   <div class="content" id="panel2-3">
     <p><div id="locations"><%= render :partial => "home/locations_searched_from_home" %></div></p>
  </div>
  
  <div class="content" id="panel2-2">
	 <p><div id="profiles"><%= render :partial => "home/profiles_searched_from_home" %></div></p>
	 </div>
</div>